
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fed-rl-app
  namespace: dynamic-graph-fed-rl-staging
  labels:
    app: fed-rl-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fed-rl-app
  template:
    metadata:
      labels:
        app: fed-rl-app
        version: v1
    spec:
      containers:
      - name: fed-rl-app
        image: dynamic-graph-fed-rl:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: REGION
          value: "us-east-1"
