version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"