version: '3.8'

services:
  consciousness:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: universal-quantum-consciousness
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - CONSCIOUSNESS_SECURITY_LEVEL=HIGH
    ports:
      - "8000:8000"
    volumes:
      - consciousness_data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "print('Healthy')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - consciousness_network

  # Optional: Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: consciousness-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - consciousness_network

  grafana:
    image: grafana/grafana:latest
    container_name: consciousness-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=consciousness_admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - consciousness_network

volumes:
  consciousness_data:
  prometheus_data:
  grafana_data:

networks:
  consciousness_network:
    driver: bridge
