name: Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'src/**', 'README.md' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'src/**', 'README.md' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    
    - name: Build Sphinx documentation
      run: |
        cd docs/
        sphinx-apidoc -o source/ ../src/
        sphinx-build -b html source/ _build/html/
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/_build/html/

    - name: Upload docs artifact for PR
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: docs-preview
        path: docs/_build/html/

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

  docs-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Comment PR with docs preview
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Create comment with preview link
          const comment = `## 📚 Documentation Preview
          
          The documentation has been built successfully! 
          
          **Preview:** Documentation preview is available as a workflow artifact.
          
          **Changes:** This PR includes documentation changes.
          
          ---
          *This comment is automatically generated.*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });